"""Category taxonomy matching CRED Money style."""

CATEGORIES: dict[str, list[str]] = {
    "food_dining": ["restaurants", "groceries", "food_delivery", "cafe", "bakery", "dairy", "meat_fish"],
    "shopping": ["online", "clothing", "electronics", "home_furnishing", "accessories", "footwear", "cosmetics"],
    "transport": ["fuel", "cab", "auto", "parking", "toll", "metro", "bus", "train", "flight"],
    "bills_utilities": ["electricity", "water", "gas", "internet", "phone", "dth", "broadband", "recharge"],
    "entertainment": ["movies", "streaming", "gaming", "events", "sports", "music", "books"],
    "health_fitness": ["pharmacy", "hospital", "doctor", "gym", "supplements", "lab_test", "dental", "optical"],
    "education": ["courses", "books", "tuition", "school", "college", "certification", "coaching"],
    "investment": ["stocks", "mutual_funds", "fd", "rd", "gold", "crypto", "ppf", "nps", "bonds"],
    "emi_loans": ["home_loan", "car_loan", "personal_loan", "education_loan", "gold_loan"],
    "insurance": ["life", "health", "vehicle", "term", "home"],
    "subscriptions": ["monthly", "yearly", "streaming", "saas", "membership"],
    "transfers": ["self_transfer", "family", "friends", "salary"],
    "cash_withdrawal": ["atm"],
    "tax_government": ["income_tax", "gst", "challan", "stamp_duty", "registration"],
    "rent": ["house_rent", "office_rent"],
    "travel": ["hotel", "booking", "airbnb", "oyo", "visa"],
    "personal_care": ["salon", "spa", "laundry"],
    "charity": ["donation", "temple", "ngo"],
    "others": ["uncategorized", "misc"],
}

CATEGORY_DISPLAY_NAMES: dict[str, str] = {
    "food_dining": "Food & Dining",
    "shopping": "Shopping",
    "transport": "Transport",
    "bills_utilities": "Bills & Utilities",
    "entertainment": "Entertainment",
    "health_fitness": "Health & Fitness",
    "education": "Education",
    "investment": "Investment",
    "emi_loans": "EMI & Loans",
    "insurance": "Insurance",
    "subscriptions": "Subscriptions",
    "transfers": "Transfers",
    "cash_withdrawal": "Cash Withdrawal",
    "tax_government": "Tax & Government",
    "rent": "Rent",
    "travel": "Travel",
    "personal_care": "Personal Care",
    "charity": "Charity & Donations",
    "others": "Others",
}

SUB_CATEGORY_DISPLAY: dict[str, str] = {
    "restaurants": "Restaurants",
    "groceries": "Groceries",
    "food_delivery": "Food Delivery",
    "cafe": "Cafe & Coffee",
    "online": "Online Shopping",
    "clothing": "Clothing & Apparel",
    "electronics": "Electronics & Gadgets",
    "fuel": "Fuel & Petrol",
    "cab": "Cab & Ride",
    "auto": "Auto Rickshaw",
    "electricity": "Electricity",
    "internet": "Internet & WiFi",
    "phone": "Mobile Recharge",
    "pharmacy": "Pharmacy & Medicine",
    "hospital": "Hospital & Clinic",
    "gym": "Gym & Fitness",
    "stocks": "Stocks",
    "mutual_funds": "Mutual Funds",
    "home_loan": "Home Loan EMI",
    "car_loan": "Car Loan EMI",
    "atm": "ATM Withdrawal",
    "self_transfer": "Self Transfer",
    "salary": "Salary",
    "income_tax": "Income Tax",
}
